### ISSUE TITLE
Fix folder structure

### ISSUE THREAD

**Issue by alj-b** [TechLabs-Berlin/wt23-naturdoc#35]
Copied from Slack:

We need to think about how the repository should be best organised.

This is the current structure on branch main of the wt23-naturdoc repository as of Mar 20 (I summarised files contained in folders once I got two levels in):
```
├── backend
│   ├── .gitignore
│   ├── README.md
│   ├── app.js
│   ├── middleware.js
│   ├── package-lock.json
│   ├── package.json
│   └── models
│   │   └── # .js models
│   └── sample_data
│   │   └── # sample/dummy data (?)
│   └── utilities
│       └── # .js utilities
├── ds
│   ├── README.md
│   ├── requirements.txt
│   └── data
│   │   └── # original sources of data
│   └── notebooks
│   │   └── # Jupyter notebooks exploring, transforming, scraping data
│   └── output
│       └── # transformed data as .csv and .json files
│   └── src
│       └── # the DS API as well as python script to populate database
├── reactApp
│   ├── .gitignore
│   ├── README.md
│   ├── jsconfig.json
│   ├── package-lock.json
│   ├── package.json
│   └── public
│   │   └── # images, icons, text files
│   └── src
│       │── # .js for react
│       │── assets
│       │   └── # stuff
│       │── components
│       │   └── # more folders
│       │── data
│       │   └── # axios requests to BE
│       └── pages
│           └── # .js pages
└── .gitignore
```
UX also needs to add their documents at some point, and then there will also be a folder containing our presentations and so on. We also have 3 or so gitignore files right now, which we could probably consolidate (readmes are fine of course). In general what I'd propose is that we create an app folder containting the folders for frontend, backend and the ds api. Then there will also be a ds (for everything that's not the API), ux folder, a main README.md for the entire project, and other files required by TechLabs (blogpost, summary, folders for documents, images,...)

A very rough proposed layout:
```
├── app
│   └── backend
│   │   └── # all backend folders and files, README.md, package.json,...
│   └── frontend
│   │   └── # all react folders and files, README.md, package.json,...
│   └── remedyApi # better name please
│       └── # all files for the remedy recommendation script and API, README.md, requirements.txt,...
├── ds
│   └── data
│   │   └── # original sources of data
│   └── notebooks
│   │   └── # Jupyter notebooks exploring, transforming, scraping data
│   └── output
│       └── # transformed data as .csv and .json files
│   └── scripts
│       └── # python script to populate database as it's not part of the API
├── ux
│   ├── ux
│   ├── doing
│   ├── their
│   └── thing
├── README.md
├── .gitignore
├── other
├── stuff
├── required
├── by
└── TechLabs (files and folders)
```

**Comment by alj-b** [comment]
Copied from Slack:

"[...] It should be quick to do and it shouldn't break anything, but well... if coding has taught me anything, it's to never trust a modal verb :laughing:"
-> it did indeed break something, so let's do it after the final presentation.

"Let's do it later then once our app code is pretty much done. I think it could also get a bit confusing if there still are a lot of existing branches to push and the files change location (= were all renamed) in the meantime."

**Comment by rjeantet** [comment]
Hello hello !
I am on this this morning, testing out and if all good will push to preprod

@alj-b: what files / folder exactly need to go in app from DS (is it the whole src folder? And how should we rename it?)
I could do it all at once, or take care of moving only FE and BE it app and then you move the DS folders and files needed into app? How should we go about it?
