### ISSUE TITLE
Consistency of naming

### ISSUE THREAD

**Issue by alj-b** [TechLabs-Berlin/wt23-naturdoc#36]
Once we have decided on the final naming scheme for the remedy variables, update database and code interacting with the database accordingly

**Comment by rjeantet** [comment]
Awesome that we have all (DS/FE/BE) updated and pushed our code  but there are still some inconsistencies (for remedies it seems that some fields are missing: symptomsMatched, fullMatch, doctorAlert, iconReference, ratings). 
Also some different calls (ex: BE calls MedicalUses, Fe calls symptomsMatched) that causes some content not to render.
Would be good to have a session the three of us to rediscuss / double check

**Comment by alj-b** [comment]
Done!
