### ISSUE TITLE
send all necessary params to FE from DS recommendation script

### ISSUE THREAD

**Issue by ChristinaLisa** [TechLabs-Berlin/wt23-naturdoc#42]
at the moment, we only send remedyName, rating and symptom back to the FE. We need to decide which info to display

**Comment by rjeantet** [comment]
On the remedy result cards, we need:
(_id)
symptomsMatched
iconReference
remedyName
ratingAverage
ERRATUM + totalNumberofRatings

**Comment by ChristinaLisa** [comment]
done 🏁 - MR: https://github.com/TechLabs-Berlin/wt23-naturdoc/pull/82
