### ISSUE TITLE
Remove icons from app

### ISSUE THREAD

**Issue by rjeantet** [TechLabs-Berlin/wt23-naturdoc#63]
- remove from FE: mandatory
- remove from DB DS/BE (iconReference): not necessary/important (?)

**Comment by alj-b** [comment]
From my end, we can just leave it in as a "future extension"

**Comment by rjeantet** [comment]
Yes, I also just commented out so that if needed later on it is ready. And I think Christina did not have it at all in her DB anyway, so we can close this issue 🥳
